//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSKAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKIOSKEntities : DbContext
    {
        public QLKIOSKEntities()
            : base("name=QLKIOSKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_kiosk_constr> v_kiosk_constr { get; set; }
    
        public virtual int sp_api_SetToken(string makiosk, string token)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_api_SetToken", makioskParameter, tokenParameter);
        }
    }
}
