//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSKAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKIOSKClientEntities : DbContext
    {
        public QLKIOSKClientEntities()
            : base("name=QLKIOSKClientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_api_BuoiAn> v_api_BuoiAn { get; set; }
        public virtual DbSet<v_api_ChiTietGiamGiaTheoSL> v_api_ChiTietGiamGiaTheoSL { get; set; }
        public virtual DbSet<v_api_DotKhuyenMai> v_api_DotKhuyenMai { get; set; }
        public virtual DbSet<v_api_HinhThucThanhToan> v_api_HinhThucThanhToan { get; set; }
        public virtual DbSet<v_api_LoaiMatHang> v_api_LoaiMatHang { get; set; }
        public virtual DbSet<v_api_MatHang> v_api_MatHang { get; set; }
        public virtual DbSet<v_api_QuangCao> v_api_QuangCao { get; set; }
    
        public virtual ObjectResult<sp_api_getBuoiAn_Result> sp_api_getBuoiAn(string makiosk)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getBuoiAn_Result>("sp_api_getBuoiAn", makioskParameter);
        }
    
        public virtual ObjectResult<sp_api_getChiTietGiamGiaTheoSL_Result> sp_api_getChiTietGiamGiaTheoSL(Nullable<int> makm)
        {
            var makmParameter = makm.HasValue ?
                new ObjectParameter("makm", makm) :
                new ObjectParameter("makm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getChiTietGiamGiaTheoSL_Result>("sp_api_getChiTietGiamGiaTheoSL", makmParameter);
        }
    
        public virtual ObjectResult<sp_api_getDotKhuyenMai_Result> sp_api_getDotKhuyenMai(string makiosk)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getDotKhuyenMai_Result>("sp_api_getDotKhuyenMai", makioskParameter);
        }
    
        public virtual ObjectResult<sp_api_getLoaiMatHang_Result> sp_api_getLoaiMatHang(string makiosk)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getLoaiMatHang_Result>("sp_api_getLoaiMatHang", makioskParameter);
        }
    
        public virtual ObjectResult<sp_api_getMatHang_Result> sp_api_getMatHang(string makiosk, Nullable<int> malmh, Nullable<int> maba)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            var malmhParameter = malmh.HasValue ?
                new ObjectParameter("malmh", malmh) :
                new ObjectParameter("malmh", typeof(int));
    
            var mabaParameter = maba.HasValue ?
                new ObjectParameter("maba", maba) :
                new ObjectParameter("maba", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getMatHang_Result>("sp_api_getMatHang", makioskParameter, malmhParameter, mabaParameter);
        }
    
        public virtual ObjectResult<sp_api_getQuangCao_Result> sp_api_getQuangCao(string makiosk)
        {
            var makioskParameter = makiosk != null ?
                new ObjectParameter("makiosk", makiosk) :
                new ObjectParameter("makiosk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_api_getQuangCao_Result>("sp_api_getQuangCao", makioskParameter);
        }
    }
}
