//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_kiosk_constr
    {
        public string MAKO { get; set; }
        public string ConnectStr { get; set; }
        public string MaToken { get; set; }
    }
}
